export const experiencesMock = [
  {
    id: 1,
    role: 'Desenvolvedor Full Stack',
    company: 'Grupo Sina',
    workingDate: 'Setembro de 2023 - Até o momento',
    description:
      'Empresas do mesmo grupo. Responsabilidades como criação de dashboard para controle de usuários e fluxos, sites jogos online como cassino, poker, crash, plataformas de apostas esportivas e e-commerce. Experiência com desenvolvimento full stack, frontend e backend, utilizando stacks como JavaScript, TypeScript, React, NextJs, NodeJs, Styled Components, Python, Django Rest Framework, e desenvolvimento de APIs RESTFull.',
    tecnologies: [
      'JavaScript',
      'TypeScript',
      'NextJs',
      'NodeJs',
      'Tailwind CSS',
      'NestJs',
      'Docker',
      'Vercel',
    ],
    icons: [
      '/javascriptIcon.png',
      '/typescriptIcon.png',
      '/nextjsIcon.png',
      '/nodejsIcon.png',
      '/tailwindIcon.png',
      '/nestjsIcon.png',
      '/dockerIcon.png',
      '/vercelIcon.svg',
    ],
  },
  {
    id: 2,
    role: 'Desenvolvedor Full Stack',
    company: 'F12.bet / GDS TEC',
    workingDate: 'Dezembro de 2022 - Abril de 2023',
    description:
      'Empresas do mesmo grupo. Responsabilidades como criação de dashboard para controle de usuários e fluxos, sites jogos online como cassino, poker, crash, plataformas de apostas esportivas e e-commerce. Experiência com desenvolvimento full stack, frontend e backend, utilizando stacks como JavaScript, TypeScript, React, NextJs, NodeJs, Styled Components, Python, Django Rest Framework, e desenvolvimento de APIs RESTFull.',
    tecnologies: [
      'JavaScript',
      'TypeScript',
      'React',
      'NextJs',
      'NodeJs',
      'Styled Components',
      'Python',
      'Django Rest Framework',
    ],
    icons: [
      '/javascriptIcon.png',
      '/typescriptIcon.png',
      '/nextjsIcon.png',
      '/nodejsIcon.png',
      '/tailwindIcon.png',
      '/nestjsIcon.png',
      '/dockerIcon.png',
      '/vercelIcon.svg',
    ],
  },
  {
    id: 3,
    role: 'Estudante',
    company: 'Trybe',
    workingDate: 'Março de 2022 - Março de 2023',
    description:
      'TRYBE - Escola de Programação e desenvolvimento web: Desenvolvimento Web, Desenvolvedor Web Full Stack (2022). Fundamentos do desenvolvimento web: Unix, Shell e GitHub, HTML, CSS, JavaScript, DOM, testes unitários, higher-order-functions; 2 Desenvolvimento front-end: React, NextJs, Redux, testes automatizados, styled-components, React-toastify, React Hook Forms, Yup, Joi, CORS; Desenvolvimento back-end: Docker, SQL, NoSQL, NodeJs, Arquiteturas de software com foco na arquitetura MSC (model, service e controller), ORM, autenticações com JWT, TypeScript, programação orientada a objetos, MongoDB, PostgreSQL, APIs REST, APIs orientadas a objeto,princípios SOLID e deploy de aplicações em nuvem com Railway; Ciências da computação: Python, Flask, Django Rest Framework, padrões de projeto, raspagem de dados, algoritmos e estrutura de dados;',
    tecnologies: [
      'JavaScript',
      'TypeScript',
      'React',
      'NextJs',
      'NodeJs',
      'Styled Components',
      'Python',
      'Django Rest Framework',
    ],
    icons: [
      '/javascriptIcon.png',
      '/typescriptIcon.png',
      '/nextjsIcon.png',
      '/nodejsIcon.png',
      '/tailwindIcon.png',
      '/nestjsIcon.png',
      '/dockerIcon.png',
      '/vercelIcon.svg',
    ],
  },
]
